import { readdirSync, readFileSync } from 'fs';
import { join } from 'path';

import { processConfig, validateConfig } from '../../configProcessor';

const dir = join(__dirname, '__fixtures__', 'golden');
const presets = readdirSync(dir)
  .filter((file) => file.endsWith('.input.json'))
  .map((file) => file.replace('.input.json', ''));

const read = (file: string) => JSON.parse(readFileSync(join(dir, file), 'utf8'));

describe('v3 golden manifests (generated by the original 1.20.x implementation)', () => {
  it('covers every preset that existed on 1.20.x', () => {
    expect(presets.length).toBe(24);
  });

  it.each(presets)('%s: validates and produces the same manifest', (preset) => {
    const config = { ...read(`${preset}.input.json`), version: 3 };

    expect(() => validateConfig(config)).not.toThrow();
    expect(processConfig(config)).toEqual(read(`${preset}.manifest.json`));
  });
});
