import * as crypto from 'node:crypto';

export default crypto;
export var { Cipher } = crypto;
export var { Decipher } = crypto;
export var { DiffieHellman } = crypto;
export var { DiffieHellmanGroup } = crypto;
export var { Hash } = crypto;
export var { Hmac } = crypto;
export var { Sign } = crypto;
export var { Verify } = crypto;
export var { constants } = crypto;
export var { createCipheriv } = crypto;
export var { createDecipheriv } = crypto;
export var { createDiffieHellman } = crypto;
export var { createDiffieHellmanGroup } = crypto;
export var { createECDH } = crypto;
export var { createHash } = crypto;
export var { createHmac } = crypto;
export var { createSign } = crypto;
export var { createVerify } = crypto;
export var { getCiphers } = crypto;
export var { getDiffieHellman } = crypto;
export var { getHashes } = crypto;
export var { pbkdf2 } = crypto;
export var { pbkdf2Sync } = crypto;
export var { privateDecrypt } = crypto;
export var { privateEncrypt } = crypto;
export var { pseudoRandomBytes } = crypto;
export var { publicDecrypt } = crypto;
export var { publicEncrypt } = crypto;
export var { randomBytes } = crypto;
export var { randomFill } = crypto;
export var { randomFillSync } = crypto;
export var { getRandomValues } = crypto;
export var { randomUUID } = crypto;
export var { generateKeyPair } = crypto;

// Export Web Crypto API from globalThis.crypto (edge runtime)
export var webcrypto = (typeof globalThis !== 'undefined' && globalThis.crypto) || crypto.webcrypto;
export var subtle = webcrypto?.subtle;
export var CryptoKey = (typeof globalThis !== 'undefined' && globalThis.CryptoKey) || crypto.CryptoKey;
export var KeyObject = crypto.KeyObject;
