name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Run linting
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check

      - name: Build
        run: pnpm compile

  test_unit:
    name: Unit Tests
    needs: lint_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Build
        run: pnpm compile

      - name: Run unit tests
        run: pnpm test

  test-e2e:
    name: E2E Tests
    needs: lint_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Build
        run: pnpm compile

      - name: Run E2E tests
        run: pnpm test:e2e
