name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Build Azion package
        run: pnpm run compile

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          publish-script: pnpm exec changeset publish
          commit-message: 'chore: version packages'
        env:
          NODE_ENV: 'production'
