name: SCC Complexity Check

on:
  pull_request:
    branches: [main]

jobs:
  scc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: aziontech/scc_check@main
